name: blocks_game
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  flame: ^0.25.0
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/blocks/block_black.png
    - assets/images/blocks/block_blue_black.png
    - assets/images/blocks/block_red.png
    - assets/images/blocks/block_blue_red.png
    - assets/images/blocks/red.png
    - assets/images/blocks/blue.png
    - assets/images/blocks/green.png
    - assets/images/blocks/orange.png
    - assets/images/blocks/yellow.png